# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 7da021b028b936b52242be3b649c21ab434a3f41

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: FacultadHumanidades@localhost

authentication:
    xauth:
        secret: myXAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

swagger:
    title: FacultadHumanidades API
    description: FacultadHumanidades applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    
preguntas:
    cantidad: 5